version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spimex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api-service:
    build: ./api-service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  parser-service:
    build: ./parser-service
    command: python parser.py
    depends_on:
      - postgres