name: spimex-trading-api

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spimex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api-service:
    build: ./api_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres/spimex_db"
    restart: unless-stopped

  parser-service:
    build: ./parser_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres/spimex_db"
    restart: on-failure
    
volumes:
  postgres_data:
  redis_data: