[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "spimex-trading-api"
version = "0.1.0"
description = "API and parser for Spimex trading data"

[tool.setuptools.package-dir]
"" = "src"